api_keys:
    - application: "one app"
      key: "not-a-real-api-key-but-it-needs-to-be-long"
      kind: "log"
    - application: "ci/cd"
      key: "this-is-a-long-key-that-provides-admin-access"
      kind: "admin"

serve:
  host: "0.0.0.0"
  port: 9999

app:
  gin_mode: "debug"
  storage: "sqlite"

sqlite:
  path: "./data"

s3:
  bucket: "blue-bucket"
  scheme: "http"
  host: "localhost"
  port: "3900"
  disableSSL: true
  s3ForcePathStyle: true
