api_keys:
    - application: "one app"
      key: "not-a-real-api-key-but-it-needs-to-be-long"
      kind: "log"
    - application: "ci/cd"
      key: "this-is-a-long-key-that-provides-admin-access"
      kind: "admin"

serve:
  host: "localhost"
  port: 8888

app:
  gin_mode: "debug"
  storage: "sqlite"

sqlite:
  path: "."

minio:
  host: "minio"
  port: "8000"
  disableSSL: true
  s3ForcePathStyle: true
