api_keys:
    - application: "one app"
      key: "73ed42a40dcd82f1fa43de58fa63c5e5e6a4137672af8948ad10104da5cea045"
      kind: "log"
    - application: "ci/cd"
      key: "c68df289d7f0ec5ff40cf14ae767b73d342c563c203d424ea054d85fb3fdbaf1"
      kind: "admin"
    - application: "analysis"
      key: "b36f7281166e2dfe18567ec06547f36e3b5e42141c310a41df098a67c3cda29b"
      kind: "read-only"

serve:
  host: "0.0.0.0"
  # When cert/key are "mock", we run with TLS.
  port: 8443
  cert: "mock" 
  key: "mock"

app:
  # "debug" or "release"
  gin_mode: "release"
  storage: "sqlite"
  event_buffer_length: 100
  event_buffer_flush_seconds: 1
  # Keeping the seed constant means the same
  # events get hashed to the same integers.
  # Changing this changes the dictionary.
  hash_seed: 42

  # storage: "default"

sqlite:
  path: "./data"
  # To test without generating files, tell SQLite
  # to create an in-memory database.
  # path: ":memory:"

s3:
  bucket: "blue-bucket"
  scheme: "http"
  host: "localhost"
  port: "3900"
  disableSSL: true
  s3ForcePathStyle: true
