services:
  itslog:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./container-config.yaml:/app/config.yaml
      - ./data:/data
    ports:
      - "8888:8888"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
  garage:
    image: dxflrs/garage:v2.1.0
    volumes:
      - ./data:/var/lib/garage
      - ./garage.toml:/etc/garage.toml:ro
    environment:
      GARAGE_RPC_SECRET: "aaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbccccccccccccccccdddddddddddddddd"
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"